### ISSUE TITLE
有没有人给你反馈过 你的源添加不上去

### ISSUE THREAD

**Issue by dingshaohua-com** [zhaoboy9692/repo#1]
有没有人给你反馈过 你的源添加不上去

**Comment by dingshaohua-com** [comment]
源的问题 我已经解决了 基于你的源，我自己搞了个副本就好了。
现在出现另一个问题。
不兼容  

和我已有的插件不兼容

而这个插件我又不能降级  其他几个模块依赖

![1](https://github.com/zhaoboy9692/repo/assets/18003391/d88ba535-9548-42c8-80d6-20b52731e782)
![2](https://github.com/zhaoboy9692/repo/assets/18003391/8cee3ff8-2953-45f1-a26a-93b7af0bd699)

**Comment by zhaoboy9692** [comment]
好的 抽时间解决下  添加不上是因为科学网的问题吧
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月16日 16:36 |
| 收件人 | zhaoboy9692/repo ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [zhaoboy9692/repo] 有没有人给你反馈过 你的源添加不上去 (Issue #1) |

源的问题 我已经结局了 基于你的源，我自己搞了个副本就好了。
现在出现另一个问题。
不兼容

和我已有的插件不兼容

而这个插件我又不能降级 其他几个模块依赖

**Comment by zhaoboy9692** [comment]
着急的话 你可以解压包 改下里面的依赖
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月16日 16:36 |
| 收件人 | zhaoboy9692/repo ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [zhaoboy9692/repo] 有没有人给你反馈过 你的源添加不上去 (Issue #1) |

源的问题 我已经结局了 基于你的源，我自己搞了个副本就好了。
现在出现另一个问题。
不兼容

和我已有的插件不兼容

而这个插件我又不能降级 其他几个模块依赖

**Comment by zhaoboy9692** [comment]
> 源的问题 我已经解决了 基于你的源，我自己搞了个副本就好了。 现在出现另一个问题。 不兼容
> 
> 和我已有的插件不兼容
> 
> 而这个插件我又不能降级 其他几个模块依赖
> 
> ![1](https://user-images.githubusercontent.com/18003391/260951026-d88ba535-9548-42c8-80d6-20b52731e782.jpg) ![2](https://user-images.githubusercontent.com/18003391/260951041-8cee3ff8-2953-45f1-a26a-93b7af0bd699.jpg)

已经修复，更新下源

**Comment by dingshaohua-com** [comment]
好的

**Comment by dingshaohua-com** [comment]
对了 大佬 能教我下怎么打包吗  怎么把frp打包成deb吗
期待您有时间能抽空做个教程 或者指导一下
