### ISSUE TITLE
可不可以添加一下最新版的frpc，4.8版本有点问题

### ISSUE THREAD

**Issue by mxdlzg** [zhaoboy9692/repo#2]
或者大佬能说一下怎么针对的ios环境编译的frpc吗？

**Comment by zhaoboy9692** [comment]
> 或者大佬能说一下怎么针对的ios环境编译的frpc吗？

就golang正常编译为arm就行了之后 打包deb，最近有时间会更新

**Comment by mxdlzg** [comment]
> > 或者大佬能说一下怎么针对的ios环境编译的frpc吗？
> 
> 就golang正常编译为arm就行了之后 打包deb，最近有时间会更新

懂了，我在ipad上安go直接编译了一份，仓库如果能更新就更好了。先关问题了

**Comment by zhaoboy9692** [comment]
已经更新到0.51.3
| |
zxc
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Wei ***@***.***> |
| 发送日期 | 2023年09月25日 11:28 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zhaoboy9692/repo] 可不可以添加一下最新版的frpc，4.8版本有点问题 (Issue #2) |

或者大佬能说一下怎么针对的ios环境编译的frpc吗？

就golang正常编译为arm就行了之后 打包deb，最近有时间会更新

懂了，我在ipad上安go直接编译了一份，仓库如果能更新就更好了。先关问题了
